### ISSUE TITLE
Migrar Layout de CSS a Tailwind

### ISSUE THREAD

**Issue by abelpz** [idiomaspuentes/translation-teams#14]
Tarea:
Reemplazar las clases CSS actualmente definidas en Layout.css con clases de Tailwind CSS en el archivo Layout.tsx.

Detalles:
Eliminar el archivo Layout.css y sus imports una vez completada la migración.

Mantener los mismos estilos usando las utilidades de Tailwind.

Usar clases de Tailwind siguiendo el sistema de diseño del proyecto.

 **Antes (CSS en Layout.css)**
```css
.container {
   display: flex;
   gap: 1rem;
   padding: 2rem;
   align-items: center;
}
```
```jsx
<div className="container ">
  {/* Contenido */}
</div>
```

**Ahora (Tailwind en Layout.tsx)**
```jsx
<div className="flex gap-4 p-8 items-center">
  {/* Contenido */}
</div>
```

La clase `container` en el elemento div fue reemplazada por clases de Tailwind. Hacer lo mismo con todas las clases de `Layout.css` que estén siendo usadas en `Layout.jsx`
